apiVersion: v1
kind: Service
metadata:
    name: user-manage-service
spec:
    selector:
        app: user-manage-app
    type: NodePort
    ports:
    -   nodePort: 30000
        port: 8080
        protocol: TCP
        targetPort: 8080